spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/langchain-data?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8&rewriteBatchedStatements=true # MODE 使用 MySQL 模式；DATABASE_TO_UPPER 配置表和字段使用小写
    username: root
    password: root

